name: iOS Beta TestFlight

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15  # Updated to use macOS 15 runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.4.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'  # Updated to match runner's Ruby version
          bundler-cache: true

      - name: Install CocoaPods dependencies
        run: |
          which pod || sudo gem install cocoapods
          pod install --repo-update
        working-directory: Zoobox
        continue-on-error: true

      - name: Write App Store Connect API key to file
        run: echo "$APP_STORE_CONNECT_API_KEY_JSON" > ./fastlane/AuthKey.json
        env:
          APP_STORE_CONNECT_API_KEY_JSON: ${{ secrets.APP_STORE_CONNECT_API_KEY_JSON }}

      - name: Fastlane Beta
        env:
          APP_STORE_CONNECT_API_KEY_PATH: ./fastlane/AuthKey.json
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
        run: bundle exec fastlane beta